version: "3"


services:
  fami-chat-api-service:
    image: fami-chat-api-service:0.3.0
    container_name: fami-chat-api-service
    build:
      context: ./chat_api
      dockerfile: Dockerfile
    depends_on:
      - fami-tracker-store-service
    environment:
      - COLUMNS=${COLUMNS:-120}
    networks:
      - chat-network
    restart: always
    tty: true

  fami-channel-api-service:
    image: fami-channel-api-service:0.3.0
    container_name: fami-channel-api-service
    build:
      context: ./channel_api
      dockerfile: Dockerfile
    depends_on:
      - fami-tracker-store-service
    environment:
      - COLUMNS=${COLUMNS:-120}
    networks:
      - chat-network
    restart: always
    tty: true

  fami-gpt-api-service:
    image: fami-gpt-api-service:0.3.0
    container_name: fami-gpt-api-service
    build:
      context: ./gpt_api
      dockerfile: Dockerfile
    depends_on:
      - fami-tracker-store-service
    environment:
      - COLUMNS=${COLUMNS:-120}
    networks:
      - chat-network
    restart: always
    tty: true

  fami-tracker-store-service:
    image: postgres:11-bullseye
    container_name: fami-tracker-store-service
    networks:
      - chat-network
    restart: always


networks:
  chat-network:
      name: chat-network
