version: "3"


services:
  chat-api-service:
    image: chat-api-service:0.2.0
    container_name: chat-api-service
    build:
      context: ./chat_api
      dockerfile: Dockerfile
    depends_on:
      - tracker-store-service
    environment:
      - COLUMNS=${COLUMNS:-120}
    networks:
      - chat-network
    restart: always
    tty: true

  channel-api-service:
    image: channel-api-service:0.2.0
    container_name: channel-api-service
    build:
      context: ./channel_api
      dockerfile: Dockerfile
    depends_on:
      - tracker-store-service
    environment:
      - COLUMNS=${COLUMNS:-120}
    networks:
      - chat-network
    restart: always
    tty: true

  tracker-store-service:
    image: postgres:11-bullseye
    container_name: tracker-store-service
    networks:
      - chat-network
    restart: always


networks:
  chat-network:
      name: chat-network
